# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MattyG
description: A silly little personal website
repository: https://github.com/meawoppl
# baseurl: /
url: https://meawoppl.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: standard  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: MattyG
email: meawoppl@gmail.com

navigation:
  - text: Home
    url: /

  - text: Press
    url: /
  - text: Nature Outlook 2019
    url: "https://www.nature.com/articles/d41586-019-02875-z"

  - text: Burning Man Honoraria 2019
    url: "https://journal.burningman.org/2019/02/burning-man-arts/brc-art/introducing-the-2019-black-rock-city-honoraria/"

  - text: J. Path. Info. 2017
    url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5609355/"

  - text: Burner Podcast 2016
    url: "http://www.burnerpodcast.com/previous-episodes/category/matthew-goodman"

  - text: TechCrunch 2016
    url: "https://techcrunch.com/2016/07/11/3scan-raises-14-million-for-a-robotic-microscope-that-could-accelerate-drug-discovery/"

  - text: Forbes 2015
    url: "https://www.forbes.com/sites/joshwolfe/2015/01/28/digital-imaging-on-the-cutting-edge-of-tissue-analysis/"

  - text: Breakout Labs 2016
    url: "https://medium.com/breakout-labs/3scan-announces-milestones-plans-to-expand-team-in-2016-818511e4712d"

  - text: Nature Methods 2013
    url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3982327/"

  - text: O'Reilly Radar 2013
    url: "http://radar.oreilly.com/2013/01/science-as-a-service.html"

  - text: FastCompany 2011
    url: "https://www.fastcompany.com/1800957/need-lab-outer-space-try-scienceexchange-airbnb-weird-science"

  - text: PetaPixel 2011
    url: "https://petapixel.com/2011/10/14/mesmerizing-time-lapse-of-burning-man-shows-5-weeks-in-5-minutes/"

  - text: HackADay 2011
    url: "https://hackaday.com/2011/06/08/create-and-conflagrate-giant-modeled-sculptures-with-kinect-and-cnc/"

social:
  - service: github
    username: meawoppl
    link: https://github.com/meawoppl
  - service: facebook
    username: meawoppl
    link: https://www.facebook.com/meawoppl
  - service: medium
    username: meawoppl
    link: https://medium.com/@meawoppl
  - service: twitter
    username: meawoppl
    link: https://twitter.com/meawoppl
  - service: google
    username: meawoppl
    link: https://plus.google.com/111419704801292205314
# Plugins
gems:
  - jekyll-seo-tag
