# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MattyG
description: A silly little personal website
repository: https://github.com/meawoppl
# baseurl: /
url: https://meawoppl.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: standard  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: MattyG
email: meawoppl@gmail.com

navigation:
  - text: Home
    url: /
  - text: PetaPixel 2011
    url: "https://petapixel.com/2011/10/14/mesmerizing-time-lapse-of-burning-man-shows-5-weeks-in-5-minutes/"

  - text: HackADay 2011
    url: "https://hackaday.com/2011/06/08/create-and-conflagrate-giant-modeled-sculptures-with-kinect-and-cnc/"
  # - text: Software
  #   url: /software

social:
  - service: github
    username: meawoppl
    link: https://github.com/meawoppl
  - service: facebook
    username: meawoppl
    link: https://www.facebook.com/meawoppl
  - service: medium
    username: meawoppl
    link: https://medium.com/@meawoppl
  - service: twitter
    username: meawoppl
    link: https://twitter.com/meawoppl
  - service: google
    username: meawoppl
    link: https://plus.google.com/111419704801292205314
# Plugins
gems:
  - jekyll-seo-tag
